<img src="../reports/figures/logotypes/f1.png" alt="F1 logo" width="250"/>

# Formula 1 World Championship (1950 - 2024)

### Proposito del Notebook

Este notebook de la Formula 1 tiene como proposito aprender a ordenar los datos de los datasets y realizar operaciones basicas para aprender a ordenar los datos para analisis de datos

In [1]:
import sys
import pandas as pd
import numpy as np

### Listando los circuitos de carrera de la fromula 1

In [14]:
df_circuits = pd.read_csv("../data/circuits.csv" , index_col = 0)
df_circuits

,circuitRef,name,location,country,lat,lng,alt,url
circuitId,,,,,,,,
1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...
75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,12,http://en.wikipedia.org/wiki/Losail_Internatio...
79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,0,http://en.wikipedia.org/wiki/Miami_Internation...

### Contar Circuitos por Paises

In [8]:
circuits_by_country_count = df_circuits.groupby("country").size()
circuits_by_country_count

country
Argentina         1
Australia         2
Austria           2
Azerbaijan        1
Bahrain           1
Belgium           3
Brazil            2
Canada            3
China             1
France            7
Germany           3
Hungary           1
India             1
Italy             4
Japan             3
Korea             1
Malaysia          1
Mexico            1
Monaco            1
Morocco           1
Netherlands       1
Portugal          4
Qatar             1
Russia            1
Saudi Arabia      1
Singapore         1
South Africa      2
Spain             6
Sweden            1
Switzerland       1
Turkey            1
UAE               1
UK                4
USA              11
United States     1
dtype: int64

### Contando el numero de elementos (circuitos) por grupo

In [11]:
circuits_by_country_element = df_circuits.groupby("country").count()
circuits_by_country_element

               circuitRef  name  location  lat  lng  alt  url
country
Argentina               1     1         1    1    1    1    1
Australia               2     2         2    2    2    2    2
Austria                 2     2         2    2    2    2    2
Azerbaijan              1     1         1    1    1    1    1
Bahrain                 1     1         1    1    1    1    1
Belgium                 3     3         3    3    3    3    3
Brazil                  2     2         2    2    2    2    2
Canada                  3     3         3    3    3    3    3
China                   1     1         1    1    1    1    1
France                  7     7         7    7    7    7    7
Germany                 3     3         3    3    3    3    3
Hungary                 1     1         1    1    1    1    1
India                   1     1         1    1    1    1    1
Italy                   4     4         4    4    4    4    4
Japan                   3     3         3    3    3    3    3
Korea                   1     1         1    1    1    1    1
Malaysia                1     1         1    1    1    1    1
Mexico                  1     1         1    1    1    1    1
Monaco                  1     1         1    1    1    1    1
Morocco                 1     1         1    1    1    1    1
Netherlands             1     1         1    1    1    1    1
Portugal                4     4         4    4    4    4    4
Qatar                   1     1         1    1    1    1    1
Russia                  1     1         1    1    1    1    1
Saudi Arabia            1     1         1    1    1    1    1
Singapore               1     1         1    1    1    1    1
South Africa            2     2         2    2    2    2    2
Spain                   6     6         6    6    6    6    6
Sweden                  1     1         1    1    1    1    1
Switzerland             1     1         1    1    1    1    1
Turkey                  1     1         1    1    1    1    1
UAE                     1     1         1    1    1    1    1
UK                      4     4         4    4    4    4    4
USA                    11    11        11   11   11   11   11
United States           1     1         1    1    1    1    1

### Generar estadisticas descriptivas para columnas numericas de los paises

In [12]:
circuits_by_country_count.describe()

count    35.000000
mean      2.200000
std       2.152973
min       1.000000
25%       1.000000
50%       1.000000
75%       3.000000
max      11.000000
dtype: float64

### Limpieza de Datos

In [15]:
#identificar celdas nulas para los circuitos 
df_circuits.isnull()

           circuitRef   name  location  country    lat    lng    alt    url
circuitId
1               False  False     False    False  False  False  False  False
2               False  False     False    False  False  False  False  False
3               False  False     False    False  False  False  False  False
4               False  False     False    False  False  False  False  False
5               False  False     False    False  False  False  False  False
...               ...    ...       ...      ...    ...    ...    ...    ...
75              False  False     False    False  False  False  False  False
76              False  False     False    False  False  False  False  False
77              False  False     False    False  False  False  False  False
78              False  False     False    False  False  False  False  False
79              False  False     False    False  False  False  False  False

[77 rows x 8 columns]

In [16]:
#cuenta los nulos por columna 
df_circuits.isnull().sum()

circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

#### Rellenar los valores nulos con cero (O)

In [19]:
df_circuits.fillna(0)

,circuitRef,name,location,country,lat,lng,alt,url
circuitId,,,,,,,,
1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...
75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,12,http://en.wikipedia.org/wiki/Losail_Internatio...
79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,0,http://en.wikipedia.org/wiki/Miami_Internation...

In [20]:
#volver a listar los nulos por columnna
df_circuits.isnull().sum()

circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

### Ordenar los datos de los circuitos por Paises

In [21]:
df_circuits.sort_values(by='country' ,ascending = False)

,circuitRef,name,location,country,lat,lng,alt,url
circuitId,,,,,,,,
80,vegas,Las Vegas Strip Street Circuit,Las Vegas,United States,36.1147,-115.1730,642,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...
79,miami,Miami International Autodrome,Miami,USA,25.9581,-80.2389,0,http://en.wikipedia.org/wiki/Miami_Internation...
63,sebring,Sebring International Raceway,Florida,USA,27.4547,-81.3483,18,http://en.wikipedia.org/wiki/Sebring_Raceway
42,dallas,Fair Park,Dallas,USA,32.7774,-96.7587,139,http://en.wikipedia.org/wiki/Fair_Park
43,long_beach,Long Beach,California,USA,33.7651,-118.1890,12,"http://en.wikipedia.org/wiki/Long_Beach,_Calif..."
...,...,...,...,...,...,...,...,...
57,zeltweg,Zeltweg,Styria,Austria,47.2039,14.7478,676,http://en.wikipedia.org/wiki/Zeltweg_Airfield
70,red_bull_ring,Red Bull Ring,Spielberg,Austria,47.2197,14.7647,678,http://en.wikipedia.org/wiki/Red_Bull_Ring
29,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.6170,58,http://en.wikipedia.org/wiki/Adelaide_Street_C...
1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
25,galvez,Autódromo Juan y Oscar Gálvez,Buenos Aires,Argentina,-34.6943,-58.4593,8,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Os...