### Pandas : Estudio y Practicas

#### Este notebook tiene el proposito general de aprender y colocar en practica el parendiaxaje sobre la libreria Pandas para la compresion ty su en analisis de datos y estudios en Machine Learnnig

In [25]:
import sys
import pandas as pd
import numpy as np

#### Serie en Pandas

Una serie Pandas es una matriz etiquetada unidimensional capaz de contener datos de cualquier tipo. Se puede crear a partir de listas de Python, matrices NumPy, diccionarios, valores escalares o datos cargados desde fuentes externas como archivos CSV, archivos Excel y bases de datos. Las etiquetas asociadas a una Serie se denominan su índice.

In [3]:
data  = np.array(['D','M'])
s = pd.Series(data)
print("Series de Panda:")
print(s)

Series de Panda:
0    D
1    M
dtype: str

In [19]:
#Otro Ejemplo Seria
numbers = [3,4,5,6,7]
series = pd.Series(numbers)
series , type(series)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.Series)

#### Pandas Data Frame

Es una estructura de datos bidimensional con ejes etiquetados (filas y columnas). Se crea cargando los conjuntos de datos del almacenamiento existente, que puede ser una base de datos SQL, un archivo CSV o un archivo Excel. Se puede crear a partir de listas, diccionarios, una lista de diccionarios, etc.

In [6]:
df = pd.DataFrame()
print(df)
lst = ['Deris' ,'Martinez' ,'Data','Science' , 'Student']
df = pd.DataFrame(lst)
print(df)

Empty DataFrame
Columns: []
Index: []
          0
0     Deris
1  Martinez
2      Data
3   Science
4   Student

#### Operaciones en Pandas

Pandas proporciona operaciones esenciales para trabajar con datos estructurados de manera eficiente. Las secciones siguientes presentan las funcionalidades más utilizadas con breves explicaciones y ejemplos sencillos

In [5]:
# Generar diccionario
data = {
    "Nombre" : ["Ana" , "Juan" , " Pedro" , "Maria", " Luis" , "Omar" , "Eliezer"],
    "Edad" : [23,25,32,21,26,24,21],
    "Ciudad" : ["Barcelona" , "Caracas","Valencia", "Caracas","Barcelona","Miranda","Valencia"]
}
data ,type(data)

({'Nombre': ['Ana', 'Juan', ' Pedro', 'Maria', ' Luis', 'Omar', 'Eliezer'],
  'Edad': [23, 25, 32, 21, 26, 24, 21],
  'Ciudad': ['Barcelona',
   'Caracas',
   'Valencia',
   'Caracas',
   'Barcelona',
   'Miranda',
   'Valencia']},
 dict)

In [6]:
#Generar un Data Frame apartir de un diccionario
df = pd.DataFrame(data=data)
df

    Nombre  Edad     Ciudad
0      Ana    23  Barcelona
1     Juan    25    Caracas
2    Pedro    32   Valencia
3    Maria    21    Caracas
4     Luis    26  Barcelona
5     Omar    24    Miranda
6  Eliezer    21   Valencia

* Exportar Data frame apartir de un diccionario

In [7]:
#Operacion con Pandas : Exportar Data Frame

df.to_csv("data.csv")

* Carga de datos: esta operación lee datos de archivos como CSV, Excel o JSON en un DataFrame

In [8]:
import_df = pd.read_csv("./data/data.csv", index_col = 0)
import_df

    Nombre  Edad     Ciudad
0      Ana    23  Barcelona
1     Juan    25    Caracas
2    Pedro    32   Valencia
3    Maria    21    Caracas
4     Luis    26  Barcelona
5     Omar    24    Miranda
6  Eliezer    21   Valencia

* Visualización y exploración de datos: después de cargar datos, es importante comprender su estructura y contenido. Estos métodos le permiten inspeccionar filas, estadísticas resumidas y metadatos.

In [20]:
import_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  7 non-null      str
 1   Edad    7 non-null      int64
 2   Ciudad  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

* Manejo de datos faltantes: los conjuntos de datos a menudo contienen valores vacíos o faltantes. Pandas proporciona funciones para detectar, eliminar o reemplazar estos valores

In [22]:
print(import_df.isnull().sum())
import_df = import_df.fillna(0)

#df.fillna(0) reemplaza los valores faltantes con 0.

Nombre    0
Edad      0
Ciudad    0
dtype: int64

* ##### Selección y filtrado de datos:
  esta operación recupera columnas, filas o registros específicos que coinciden con una condición. Permite la extracción precisa de la información requerida.

In [10]:
ages = import_df[import_df['Edad']> 25]
print(ages)

#df[df['age'] > 25] devuelve filas donde el valor "age" es mayor que 25.

   Nombre  Edad     Ciudad
2   Pedro    32   Valencia
4    Luis    26  Barcelona

In [27]:
#Nuevo ejemplo de trabajo 
data = {
    "Nombre" : [ "Ana" , "Juan" , "Pedro", "Maria","Luis","Carlos"],
    "Edad" : [22,25,28,23,20,23],
    "Ciudad" : ["valencia","cabudare","barcelona","barquisimeto","caracas","barcelona"],
    "Puntuacion" : [80 ,90 , 85 ,88 ,75,80]
}

df = pd.DataFrame(data)
df

   Nombre  Edad        Ciudad  Puntuacion
0     Ana    22      valencia          80
1    Juan    25      cabudare          90
2   Pedro    28     barcelona          85
3   Maria    23  barquisimeto          88
4    Luis    20       caracas          75
5  Carlos    23     barcelona          80

* ##### Agregar y eliminar columnas:
puede crear nuevas columnas basadas en las existentes o eliminar columnas no deseadas del DataFrame.

* ##### grupación de datos (GroupBy):
la agrupación le permite organizar los datos en categorías y calcular valores para cada grupo, por ejemplo, sumas, recuentos o promedios.

In [28]:
#agrupo datos por ciudad
grouped = df.groupby("Ciudad")
print(grouped.groups)


# Agregacion de Datos 
#calcular la suma de las edades y puntuacion por ciudad
agregate_data = grouped.agg({
    "Edad" : "mean" , #mean : PROMEDIO
    "Puntuacion" : "sum"
})

agregate_data

{'barcelona': [2, 5], 'barquisimeto': [3], 'cabudare': [1], 'caracas': [4], 'valencia': [0]}

              Edad  Puntuacion
Ciudad
barcelona     25.5         165
barquisimeto  23.0          88
cabudare      25.0          90
caracas       20.0          75
valencia      22.0          80

Agregacion de funciones Personalizadas

In [17]:
def rango(series):
    return series.max() - series.min()

##aplicar la funcion
agregate_data_custom = grouped.agg({
    "Edad" : rango,
    "Puntuacion" : rango
  })
print(agregate_data_custom)

              Edad  Puntuacion
Ciudad
barcelona        5           5
barquisimeto     0           0
cabudare         0           0
caracas          0           0
valencia         0           0


La definición abstracta de agrupación es proporcionar un mapeo de etiquetas nombres de grupos. Para crear un objeto GroupBy (más sobre qué es el objeto GroupBy más tarde), puedes hacer lo siguiente:

In [5]:
speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 80.2),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)


speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [11]:
grouped_one = speeds.groupby("class")
grouped_two = speeds.groupby(["class" , "order" ])

grouped

In [33]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)


df

     A      B         C         D
0  foo    one -0.429462  0.162622
1  bar    one -0.125741 -1.705373
2  foo    two -0.254253  1.023151
3  bar  three  0.713836 -1.307294
4  foo    two  0.368398 -0.279353
5  bar    two  0.240025 -0.326075
6  foo    one  0.545821 -0.808449
7  foo  three  1.017415  1.650744

En un DataFrame, obtenemos un objeto GroupBy llamando agroupby() . Este método devuelve una pandas.api.typing.DataFrameGroupBy instancia. Naturalmente, podríamos agrupar por columnas o, o por ambas 
 ( mas arriba se puede visualizar un pandas.api.typing.DataFrameGroupBy)

In [39]:
grouped_one = df.groupby("A")
grouped = df.groupby("B")
grouped = df.groupby(["A","B"])

DataFrame groupby siempre opera a lo largo del eje 0 (filas). Para dividir por columnas, primero haga una transposición:

In [40]:
def get_letter_type(letter) :
    if letter.lower() in 'aeiou':
        return 'vowel'
    else:
        return 'consonant'

grouped = df.T.groupby(get_letter_type)